version: "3.8"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ftcase
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  app:
    depends_on:
      - db
      - cache
      - rabbitmq
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_TABLE=ftcase
      - DB_PORT=3306
      - CACHE_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - CACHE_HOST=cache
      - QUEUE_HOST=rabbitmq
      - QUEUE_USER=guest
      - QUEUE_PASSWORD=guest
      - QUEUE_PORT=5672
    stdin_open: true
    tty: true

volumes:
  db:
  rabbitmq_data:
  cache:
    driver: local
